export const WeatherInfo = {
    '00':  {name: '晴',  englishName: 'Sunny', type: 'sunny'},
    '01':  {name: '多云',  englishName: 'Cloudy', type: 'cloudy'},
    '02':  {name: '阴',  englishName: 'Overcast', type: 'cloudy'},
    '03':  {name: '阵雨',  englishName: 'Shower', type: 'rainy'},
    '04':  {name: '雷阵雨',  englishName: 'Thundershower', type: 'rainy'},
    '05':  {name: '雷阵雨伴有冰雹',  englishName: 'Thundershower with hail', type: 'rainy'},
    '06':  {name: '雨夹雪',  englishName: 'Sleet', type: 'rainy'},
    '07':  {name: '小雨',  englishName: 'Light rain', type: 'rainy'},
    '08':  {name: '中雨',  englishName: 'Moderate rain', type: 'rainy'},
    '09':  {name: '大雨',  englishName: 'Heavy rain', type: 'rainy'},
    '10':  {name: '暴雨',  englishName: 'Storm', type: 'rainy'},
    '11':  {name: '大暴雨',  englishName: 'Heavy storm', type: 'rainy'},
    '12':  {name: '特大暴雨',  englishName: 'Severe storm', type: 'rainy'},
    '13':  {name: '阵雪',  englishName: 'Snow flurry', type: 'snowy'},
    '14':  {name: '小雪',  englishName: 'Light snow', type: 'snowy'},
    '15':  {name: '中雪',  englishName: 'Moderate snow', type: 'snowy'},
    '16':  {name: '大雪',  englishName: 'Heavy snow', type: 'snowy'},
    '17':  {name: '暴雪',  englishName: 'Snowstorm', type: 'snowy'},
    '18':  {name: '雾',  englishName: 'Foggy', type: 'cloudy'},
    '19':  {name: '冻雨',  englishName: 'Ice rain', type: 'rainy'},
    '20':  {name: '沙尘暴',  englishName: 'Duststorm', type: 'cloudy'},
    '21':  {name: '小到中雨',  englishName: 'Light to moderate rain', type: 'rainy'},
    '22':  {name: '中到大雨',  englishName: 'Moderate to heavy rain', type: 'rainy'},
    '23':  {name: '大到暴雨',  englishName: 'Heavy rain to storm', type: 'rainy'},
    '24':  {name: '暴雨到大暴雨',  englishName: 'Storm to heavy storm', type: 'rainy'},
    '25':  {name: '大暴雨到特大暴雨',  englishName: 'Heavy to severe storm', type: 'rainy'},
    '26':  {name: '小到中雪',  englishName: 'Light to moderate snow', type: 'snowy'},
    '27':  {name: '中到大雪',  englishName: 'Moderate to heavy snow', type: 'snowy'},
    '28':  {name: '大到暴雪',  englishName: 'Heavy snow to snowstorm', type: 'snowy'},
    '29':  {name: '浮尘',  englishName: 'Dust', type: 'cloudy'},
    '30':  {name: '扬沙',  englishName: 'Sand', type: 'cloudy'},
    '31':  {name: '强沙尘暴',  englishName: 'Sandstorm', type: 'cloudy'},
    '53':  {name: '霾',  englishName: 'Haze', type: 'cloudy'},
    '99':  {name: '无',  englishName: 'Unknown', type: 'cloudy'},
    '32':  {name: '浓雾',  englishName: 'Dense fog', type: 'cloudy'},
    '49':  {name: '强浓雾',  englishName: 'Strong fog', type: 'cloudy'},
    '54':  {name: '中度霾',  englishName: 'Moderate haze', type: 'cloudy'},
    '55':  {name: '重度霾',  englishName: 'Severe haze', type: 'cloudy'},
    '56':  {name: '严重霾',  englishName: 'Severe haze', type: 'cloudy'},
    '57':  {name: '大雾',  englishName: 'Dense fog', type: 'cloudy'},
    '58':  {name: '特强浓雾',  englishName: 'Extra heavy fog', type: 'cloudy'},
    '99':  {name: '无',  englishName: 'Unknown', type: 'sunny'},
    '301': {name: '雨',  englishName: 'rain', type: 'rainy'},
    '302': {name: '雪',  englishName: 'snow', type: 'snowy'},
}
